name: intl
version: 0.17.1-dev
homepage: https://github.com/dart-lang/intl
description: >-
  Contains code to deal with internationalized/localized messages, date and
  number formatting and parsing, bi-directional text, and other
  internationalization issues.

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  clock: ^1.1.0
  path: ^1.8.0

dev_dependencies:
  ffi: ^0.2.0
  fixnum: ^1.0.0
  js: ^0.6.3
  test: ^1.16.0
