name: intl
version: 0.14.0
author: Dart Team <misc@dartlang.org>
description: Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
homepage: https://github.com/dart-lang/intl
environment:
  sdk: '>=1.12.0 <2.0.0'
documentation: http://www.dartdocs.org/documentation/intl/latest
dependencies:
dev_dependencies:
  fixnum: '>=0.9.0 <0.11.0'
  unittest: '>=0.10.0 <0.12.0'
transformers:
- $dart2js:
    $exclude:
    - test/date_time_format_file_even_test.dart
    - test/date_time_format_file_odd_test.dart
    - test/find_default_locale_standalone_test.dart
    - test/intl_message_basic_example_test.dart # invalid import under pub's package-layout
